ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

USER_LIB_PATH = /home/pi/Project-Shire/experimental/source/arduinoSerial/libraries
BOARD_TAG = mega

include /usr/share/arduino/Arduino.mk
